/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.*;



/**
 *
 * @author marco
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */

    
    public Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mbBarra = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuLogin = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenu();

        jMenu10.setText("File");
        jMenuBar2.add(jMenu10);

        jMenu11.setText("Edit");
        jMenuBar2.add(jMenu11);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jMenu1.setText("Biblioteca");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        mnuLogin.setText("Login");
        mnuLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuLoginMouseClicked(evt);
            }
        });
        jMenu1.add(mnuLogin);

        mnuSalir.setText("Salir");
        mnuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuSalirMouseClicked(evt);
            }
        });
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSalir);

        mbBarra.add(jMenu1);

        setJMenuBar(mbBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuSalirMouseClicked
        // TODO add your handling code here:
        
        //antes de salir debemos cerrar todos los formularios abiertos
        System.gc();
        for (Window window : Window.getWindows())
        {
            window.dispose();
        }
        
        dispose();
        setVisible(false);
    }//GEN-LAST:event_mnuSalirMouseClicked

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void mnuLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuLoginMouseClicked
        // TODO add your handling code here:
        
//        JDialog dialogo = new JDialog();
//        Login panel = new Login();
//        dialogo.add(panel);
//        dialogo.setVisible(true);

        frmLogin f = new frmLogin();
        f.setAlwaysOnTop(true); //Esto nos permite que el jFrame sea un modal
        f.setVisible(true);

        
        


    }//GEN-LAST:event_mnuLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    public JMenu menuLogin()
    {
        return mnuLogin;
    }
    
    public void disenaFormulario(int perfil)
    {
        switch(perfil)
        {
            case 1:
                configuraAlumno();
                break;
            case 2:
                configuraDocente();
                break;
            case 3:
                configuraFuncionario();
                break;
            case 4:
                configuraAdministrador();
                break;
        }
        
    }
    
    //Configuramos el menu de Alumno
    private void configuraAlumno()
    {
        JMenu menu;
        JMenuItem jm1;
        JMenuItem jm2;
        
        setLayout(new FlowLayout());
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setVisible(true);
        menu = new JMenu("Alumno");
        
        jm1 = new JMenuItem("Mantenedor 1");
        jm1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) 
            {
                JMenuItem menuItem = (JMenuItem) e.getSource();
                String text = menuItem.getText();
                javax.swing.JOptionPane.showMessageDialog(null
                    , "Bienvenido al menu " +  jm1.getText()
                    , "Conectado"
                    , JOptionPane.ERROR_MESSAGE);
            }
        });
        
        jm2 = new JMenuItem("Mantenedor 2");
        jm2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JMenuItem menuItem = (JMenuItem) e.getSource();
                String text = menuItem.getText();
                javax.swing.JOptionPane.showMessageDialog(null
                    , "Bienvenido al menu " +  jm2.getText()
                    , "Conectado"
                    , JOptionPane.ERROR_MESSAGE);
            }
        });

        menu.add(jm1);
        menu.add(jm2);
                
        mbBarra.add(menu);
    }

    //Configura el menu de Docente
    private void configuraDocente()
    {
        JMenu menu;
        JMenuItem jm1;
        JMenuItem jm2;
        
        setLayout(new FlowLayout());
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setVisible(true);
        menu = new JMenu("Docente");
        
        jm1 = new JMenuItem("Mantenedor 1");
        jm1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) 
            {
                JMenuItem menuItem = (JMenuItem) e.getSource();
                String text = menuItem.getText();
                javax.swing.JOptionPane.showMessageDialog(null
                    , "Bienvenido al menu " +  jm1.getText()
                    , "Conectado"
                    , JOptionPane.ERROR_MESSAGE);
            }
        });
        
        jm2 = new JMenuItem("Mantenedor 2");
        jm2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JMenuItem menuItem = (JMenuItem) e.getSource();
                String text = menuItem.getText();
                javax.swing.JOptionPane.showMessageDialog(null
                    , "Bienvenido al menu " +  jm2.getText()
                    , "Conectado"
                    , JOptionPane.ERROR_MESSAGE);
            }
        });

        menu.add(jm1);
        menu.add(jm2);
                
        mbBarra.add(menu);
    }
    
    //configura el menu de Funcionaria
    private void configuraFuncionario()
    {
        JMenu menu;
        JMenuItem jm1;
        JMenuItem jm2;
        
        setLayout(new FlowLayout());
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setVisible(true);
        menu = new JMenu("Funcionario");
        
        jm1 = new JMenuItem("Mantenedor 1");
        jm1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) 
            {
                JMenuItem menuItem = (JMenuItem) e.getSource();
                String text = menuItem.getText();
                javax.swing.JOptionPane.showMessageDialog(null
                    , "Bienvenido al menu " +  jm1.getText()
                    , "Conectado"
                    , JOptionPane.ERROR_MESSAGE);
            }
        });
        
        jm2 = new JMenuItem("Mantenedor 2");
        jm2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JMenuItem menuItem = (JMenuItem) e.getSource();
                String text = menuItem.getText();
                javax.swing.JOptionPane.showMessageDialog(null
                    , "Bienvenido al menu " +  jm2.getText()
                    , "Conectado"
                    , JOptionPane.ERROR_MESSAGE);
            }
        });

        menu.add(jm1);
        menu.add(jm2);
                
        mbBarra.add(menu);
    }
    
    private void configuraAdministrador()
    {
        JMenu menu;
        JMenuItem jm1;
        JMenuItem jm2;
        
        setLayout(new FlowLayout());
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setVisible(true);
        menu = new JMenu("Administrador");
        
        jm1 = new JMenuItem("Mantenedor 1");
        jm1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) 
            {
                JMenuItem menuItem = (JMenuItem) e.getSource();
                String text = menuItem.getText();
                javax.swing.JOptionPane.showMessageDialog(null
                    , "Bienvenido al menu " +  jm1.getText()
                    , "Conectado"
                    , JOptionPane.ERROR_MESSAGE);
            }
        });
        
        jm2 = new JMenuItem("Mantenedor 2");
        jm2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JMenuItem menuItem = (JMenuItem) e.getSource();
                String text = menuItem.getText();
                javax.swing.JOptionPane.showMessageDialog(null
                    , "Bienvenido al menu " +  jm2.getText()
                    , "Conectado"
                    , JOptionPane.ERROR_MESSAGE);
            }
        });

        menu.add(jm1);
        menu.add(jm2);
                
        mbBarra.add(menu);
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar mbBarra;
    private javax.swing.JMenu mnuLogin;
    private javax.swing.JMenu mnuSalir;
    // End of variables declaration//GEN-END:variables

    
}


//class DynamicJList extends JFrame {
//
//    
//    public DynamicJList() {
//        // Set frame properties
//        
//
//    }
//
//    public static void main(String args[]) {
//        new DynamicJList();
//    }
//
//}
